---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Add Nginx config
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644

- name: Start and enable Nginx
  service:
    name: nginx
    enabled: true
    state: started
